# config.yaml

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  dbname: "maqhaa_pos"
  debug: true
externalconnection:
  productservice:
    host: localhost:50051
appport: :8010
